title: website
description: a
lang: ja
baseurl: ""
url: "https://wataruyuasa.github.io"
twitter_username: wyuasa
twitter:
  username: wyuasa
# Theme settings
minima:
  date_format: "%Y/%m/%d %H:%M"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
