title: Wataru Yuasa
author:
  name: Wataru YUASA
  email: wyuasa@kurims.kyoto-u.ac.jp
description: Research Institute for Mathematical Sciences
show_excerpts: true

social_links:
  twitter: wyuasa

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
