title: Wataru Yuasa (湯淺 亘)
author:
  name: Wataru YUASA
  email: wyuasa(at)kurims.kyoto-u.ac.jp
description: > # this means to ignore newlines until "show_excerpts:"
  Osaka Central Advanced Mathematical Institute, Osaka Metropolitan University, 3-3-138 Sugimoto, Sumiyoshi-ku Osaka 558-8585 JAPAN

show_excerpts: false # set to true to show excerpts on the homepage
language: ja

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: wyuasa
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
    
google_analytics: UA-129678431-1

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - publications.md
 - talks.md
 - misc.md
 - tikz.md
 - blog.html

# Build settings
theme: minima
minima: 
  skin: solarized

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap